# permissions for end users to view testruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testrun-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-operator
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: testrun-viewer-role
rules:
- apiGroups:
  - tests.mkurleto.io
  resources:
  - testruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tests.mkurleto.io
  resources:
  - testruns/status
  verbs:
  - get
